<?php

/*
 * This file is part of the PHP 7.4 port of the official PHP MCP SDK.
 *
 * Generated by bin/port from the Mcp\Schema namespace of mcp/sdk — change the
 * upstream source, or runtime/, and re-run it rather than editing this file.
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Mcp\Schema\Extension\Apps;

/**
 * Controls who can see and invoke a tool linked to a UI resource in an MCP App.
 *
 * @author Christopher Hertel <mail@christopher-hertel.de>
 */
final class ToolVisibility extends \Mcp\Schema\Enum\BackedEnum
{
    /** Visible to and callable by the LLM agent. */
    public const Model = 'model';
    /** Callable by the MCP App (HTML view) only, hidden from the model's tools/list. */
    public const App = 'app';

    public static function Model(): self
    {
        return self::case('Model');
    }

    public static function App(): self
    {
        return self::case('App');
    }

    /**
     * @return array<string, string|int>
     */
    protected static function definition(): array
    {
        return ['Model' => 'model', 'App' => 'app'];
    }
}
