<?php

/*
 * This file is part of the PHP 7.4 port of the official PHP MCP SDK.
 *
 * Generated by bin/port from the Mcp\Schema namespace of mcp/sdk — change the
 * upstream source, or runtime/, and re-run it rather than editing this file.
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Mcp\Schema\Extension\Apps;

use Mcp\Exception\InvalidArgumentException;

/**
 * Content Security Policy configuration for MCP App resources.
 *
 * Controls which external domains the rendered HTML app can access.
 * If omitted entirely, a restrictive default policy is applied by the host.
 *
 * @phpstan-type UiResourceCspData array{
 *     connectDomains?: string[],
 *     resourceDomains?: string[],
 *     frameDomains?: string[],
 *     baseUriDomains?: string[]
 * }
 *
 * @author Christopher Hertel <mail@christopher-hertel.de>
 */
final class UiResourceCsp implements \JsonSerializable
{
    /**
     * @var ?string[]
     *
     * @readonly
     */
    public ?array $connectDomains = null;
    /**
     * @var ?string[]
     *
     * @readonly
     */
    public ?array $resourceDomains = null;
    /**
     * @var ?string[]
     *
     * @readonly
     */
    public ?array $frameDomains = null;
    /**
     * @var ?string[]
     *
     * @readonly
     */
    public ?array $baseUriDomains = null;

    /**
     * @param ?string[] $connectDomains  domains allowed for network requests (fetch, XHR, WebSocket)
     * @param ?string[] $resourceDomains domains allowed for static resources (images, scripts, styles)
     * @param ?string[] $frameDomains    domains allowed for nested iframes
     * @param ?string[] $baseUriDomains  domains allowed for base URI origins
     */
    public function __construct(?array $connectDomains = null, ?array $resourceDomains = null, ?array $frameDomains = null, ?array $baseUriDomains = null)
    {
        $this->connectDomains = $connectDomains;
        $this->resourceDomains = $resourceDomains;
        $this->frameDomains = $frameDomains;
        $this->baseUriDomains = $baseUriDomains;
    }

    /**
     * @param UiResourceCspData $data
     */
    public static function fromArray(array $data): self
    {
        foreach (['connectDomains', 'resourceDomains', 'frameDomains', 'baseUriDomains'] as $key) {
            if (isset($data[$key]) && !\is_array($data[$key])) {
                throw new InvalidArgumentException(\sprintf('Invalid "%s" in UiResourceCsp data; expected an array.', $key));
            }
        }

        return new self(
            $data['connectDomains'] ?? null,
            $data['resourceDomains'] ?? null,
            $data['frameDomains'] ?? null,
            $data['baseUriDomains'] ?? null,
        );
    }

    /**
     * @return UiResourceCspData
     */
    public function jsonSerialize(): array
    {
        $data = [];

        // The MCP Apps spec (2026-01-26) defines "empty or omitted" identically
        // for every CSP allow-list, so empty arrays are dropped, not emitted as `[]`.
        if ($this->connectDomains) {
            $data['connectDomains'] = $this->connectDomains;
        }
        if ($this->resourceDomains) {
            $data['resourceDomains'] = $this->resourceDomains;
        }
        if ($this->frameDomains) {
            $data['frameDomains'] = $this->frameDomains;
        }
        if ($this->baseUriDomains) {
            $data['baseUriDomains'] = $this->baseUriDomains;
        }

        return $data;
    }
}
