<?php

/*
 * This file is part of the PHP 7.4 port of the official PHP MCP SDK.
 *
 * Generated by bin/port from the Mcp\Schema namespace of mcp/sdk — change the
 * upstream source, or runtime/, and re-run it rather than editing this file.
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Mcp\Schema\Extension\Apps;

use Mcp\Exception\InvalidArgumentException;

/**
 * Metadata for the _meta.ui field on resource content in a resources/read response.
 *
 * This describes the security and display requirements for the rendered HTML app.
 *
 * @phpstan-import-type UiResourceCspData from UiResourceCsp
 * @phpstan-import-type UiResourcePermissionsData from UiResourcePermissions
 *
 * @phpstan-type UiResourceContentMetaData array{
 *     csp?: UiResourceCspData,
 *     permissions?: UiResourcePermissionsData,
 *     domain?: string,
 *     prefersBorder?: bool
 * }
 *
 * @author Christopher Hertel <mail@christopher-hertel.de>
 */
final class UiResourceContentMeta implements \JsonSerializable
{
    /**
     * @readonly
     */
    public ?UiResourceCsp $csp = null;
    /**
     * @readonly
     */
    public ?UiResourcePermissions $permissions = null;
    /**
     * @readonly
     */
    public ?string $domain = null;
    /**
     * @readonly
     */
    public ?bool $prefersBorder = null;

    public function __construct(?UiResourceCsp $csp = null, ?UiResourcePermissions $permissions = null, ?string $domain = null, ?bool $prefersBorder = null)
    {
        $this->csp = $csp;
        $this->permissions = $permissions;
        $this->domain = $domain;
        $this->prefersBorder = $prefersBorder;
    }

    /**
     * @param UiResourceContentMetaData $data
     */
    public static function fromArray(array $data): self
    {
        if (isset($data['csp']) && !\is_array($data['csp'])) {
            throw new InvalidArgumentException('Invalid "csp" in UiResourceContentMeta data; expected an array.');
        }
        if (isset($data['permissions']) && !\is_array($data['permissions'])) {
            throw new InvalidArgumentException('Invalid "permissions" in UiResourceContentMeta data; expected an array.');
        }
        if (isset($data['domain']) && !\is_string($data['domain'])) {
            throw new InvalidArgumentException('Invalid "domain" in UiResourceContentMeta data.');
        }
        if (isset($data['prefersBorder']) && !\is_bool($data['prefersBorder'])) {
            throw new InvalidArgumentException('Invalid "prefersBorder" in UiResourceContentMeta data.');
        }

        return new self(
            isset($data['csp']) ? UiResourceCsp::fromArray($data['csp']) : null,
            isset($data['permissions']) ? UiResourcePermissions::fromArray($data['permissions']) : null,
            $data['domain'] ?? null,
            $data['prefersBorder'] ?? null,
        );
    }

    /**
     * @return array{
     *     csp?: UiResourceCsp,
     *     permissions?: UiResourcePermissions,
     *     domain?: string,
     *     prefersBorder?: bool
     * }
     */
    public function jsonSerialize(): array
    {
        $data = [];

        if (null !== $this->csp) {
            $data['csp'] = $this->csp;
        }
        if (null !== $this->permissions) {
            $data['permissions'] = $this->permissions;
        }
        if (null !== $this->domain) {
            $data['domain'] = $this->domain;
        }
        if (null !== $this->prefersBorder) {
            $data['prefersBorder'] = $this->prefersBorder;
        }

        return $data;
    }
}
