<?php

/*
 * This file is part of the PHP 7.4 port of the official PHP MCP SDK.
 *
 * Generated by bin/port from the Mcp\Schema namespace of mcp/sdk — change the
 * upstream source, or runtime/, and re-run it rather than editing this file.
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Mcp\Schema\Extension\Apps;

/**
 * Sandbox permissions that an MCP App resource requests from the host.
 *
 * Per spec each requested permission is a presence marker (serialized as `{}`),
 * so the wire shape is e.g. `{"geolocation": {}}`, not `{"geolocation": true}`.
 *
 * @phpstan-type UiResourcePermissionsData array{
 *     camera?: \stdClass|array<string, mixed>,
 *     microphone?: \stdClass|array<string, mixed>,
 *     geolocation?: \stdClass|array<string, mixed>,
 *     clipboardWrite?: \stdClass|array<string, mixed>
 * }
 *
 * @author Christopher Hertel <mail@christopher-hertel.de>
 */
final class UiResourcePermissions implements \JsonSerializable
{
    /**
     * @readonly
     */
    public bool $camera = false;
    /**
     * @readonly
     */
    public bool $microphone = false;
    /**
     * @readonly
     */
    public bool $geolocation = false;
    /**
     * @readonly
     */
    public bool $clipboardWrite = false;

    public function __construct(bool $camera = false, bool $microphone = false, bool $geolocation = false, bool $clipboardWrite = false)
    {
        $this->camera = $camera;
        $this->microphone = $microphone;
        $this->geolocation = $geolocation;
        $this->clipboardWrite = $clipboardWrite;
    }

    /**
     * @param UiResourcePermissionsData $data
     */
    public static function fromArray(array $data): self
    {
        // A permission is requested when its key is present with the spec's `{}`
        // marker; isset() accepts that (array/object forms) and rejects a stray null.
        return new self(
            isset($data['camera']),
            isset($data['microphone']),
            isset($data['geolocation']),
            isset($data['clipboardWrite']),
        );
    }

    /**
     * @return array<string, \stdClass>
     */
    public function jsonSerialize(): array
    {
        $data = [];

        if ($this->camera) {
            $data['camera'] = new \stdClass();
        }
        if ($this->microphone) {
            $data['microphone'] = new \stdClass();
        }
        if ($this->geolocation) {
            $data['geolocation'] = new \stdClass();
        }
        if ($this->clipboardWrite) {
            $data['clipboardWrite'] = new \stdClass();
        }

        return $data;
    }
}
