<?php

/*
 * This file is part of the PHP 7.4 port of the official PHP MCP SDK.
 *
 * Generated by bin/port from the Mcp\Schema namespace of mcp/sdk — change the
 * upstream source, or runtime/, and re-run it rather than editing this file.
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Mcp\Schema\Notification;

use Mcp\Schema\JsonRpc\Notification;

/**
 * This notification is sent from the client to the server after initialization has finished.
 *
 * @author Kyrian Obikwelu <koshnawaza@gmail.com>
 */
class InitializedNotification extends Notification
{
    public static function getMethod(): string
    {
        return 'notifications/initialized';
    }

    public static function fromParams(?array $params): self
    {
        return new self();
    }

    protected function getParams(): ?array
    {
        return null;
    }
}
