<?php

/*
 * This file is part of the PHP 7.4 port of the official PHP MCP SDK.
 *
 * Generated by bin/port from the Mcp\Schema namespace of mcp/sdk — change the
 * upstream source, or runtime/, and re-run it rather than editing this file.
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Mcp\Schema\Notification;

use Mcp\Exception\InvalidArgumentException;
use Mcp\Schema\JsonRpc\Notification;

/**
 * @author Kyrian Obikwelu <koshnawaza@gmail.com>
 */
class ResourceUpdatedNotification extends Notification
{
    /**
     * @readonly
     */
    public string $uri;

    public function __construct(string $uri)
    {
        $this->uri = $uri;
    }

    public static function getMethod(): string
    {
        return 'notifications/resources/updated';
    }

    protected static function fromParams(?array $params): Notification
    {
        if (null === $params || !isset($params['uri']) || !\is_string($params['uri'])) {
            throw new InvalidArgumentException('Invalid or missing "uri" parameter for notifications/resources/updated notification.');
        }

        return new self($params['uri']);
    }

    protected function getParams(): ?array
    {
        return [
            'uri' => $this->uri,
        ];
    }
}
