<?php

/*
 * This file is part of the PHP 7.4 port of the official PHP MCP SDK.
 *
 * Generated by bin/port from the Mcp\Schema namespace of mcp/sdk — change the
 * upstream source, or runtime/, and re-run it rather than editing this file.
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Mcp\Schema\Enum;

/**
 * How widely a cacheable result may be reused (SEP-2549).
 *
 * A security boundary, not a performance knob: `public` lets shared caches
 * serve the result to other authorization contexts, so anything shaped by who
 * asked must stay private — which is why private is the default throughout.
 *
 * @author Christopher Hertel <mail@christopher-hertel.de>
 */
final class CacheScope extends BackedEnum
{
    /** Contains no caller-specific data; any cache may share it. */
    public const Public = 'public';
    /** Reusable only within the same authorization context. */
    public const Private = 'private';

    public static function Public(): self
    {
        return self::case('Public');
    }

    public static function Private(): self
    {
        return self::case('Private');
    }

    /**
     * @return array<string, string|int>
     */
    protected static function definition(): array
    {
        return ['Public' => 'public', 'Private' => 'private'];
    }
}
