<?php

/*
 * This file is part of the PHP 7.4 port of the official PHP MCP SDK.
 *
 * Generated by bin/port from the Mcp\Schema namespace of mcp/sdk — change the
 * upstream source, or runtime/, and re-run it rather than editing this file.
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Mcp\Schema\Enum;

/**
 * How the client should collect the information an elicitation asks for.
 *
 * @author Christopher Hertel <mail@christopher-hertel.de>
 */
final class ElicitationMode extends BackedEnum
{
    /**
     * Present a form built from the requested schema, and return the filled values.
     */
    public const Form = 'form';
    /**
     * Send the user to a URL to complete the interaction out of band. The result
     * carries no content — only whether the user accepted, declined, or cancelled.
     */
    public const Url = 'url';

    public static function Form(): self
    {
        return self::case('Form');
    }

    public static function Url(): self
    {
        return self::case('Url');
    }

    /**
     * @return array<string, string|int>
     */
    protected static function definition(): array
    {
        return ['Form' => 'form', 'Url' => 'url'];
    }
}
