<?php

/*
 * This file is part of the PHP 7.4 port of the official PHP MCP SDK.
 *
 * Generated by bin/port from the Mcp\Schema namespace of mcp/sdk — change the
 * upstream source, or runtime/, and re-run it rather than editing this file.
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Mcp\Schema\Enum;

/**
 * Action taken by the user in response to an elicitation request.
 *
 * @author Johannes Wachter <johannes@sulu.io>
 */
final class ElicitAction extends BackedEnum
{
    public const Accept = 'accept';
    public const Decline = 'decline';
    public const Cancel = 'cancel';

    public static function Accept(): self
    {
        return self::case('Accept');
    }

    public static function Decline(): self
    {
        return self::case('Decline');
    }

    public static function Cancel(): self
    {
        return self::case('Cancel');
    }

    /**
     * @return array<string, string|int>
     */
    protected static function definition(): array
    {
        return ['Accept' => 'accept', 'Decline' => 'decline', 'Cancel' => 'cancel'];
    }
}
