<?php

/*
 * This file is part of the PHP 7.4 port of the official PHP MCP SDK.
 *
 * Generated by bin/port from the Mcp\Schema namespace of mcp/sdk — change the
 * upstream source, or runtime/, and re-run it rather than editing this file.
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Mcp\Schema\Enum;

/**
 * The background an icon is designed to be displayed against.
 *
 * When absent, the icon is assumed to work against any background.
 *
 * @author Christopher Hertel <mail@christopher-hertel.de>
 */
final class IconTheme extends BackedEnum
{
    public const Light = 'light';
    public const Dark = 'dark';

    public static function Light(): self
    {
        return self::case('Light');
    }

    public static function Dark(): self
    {
        return self::case('Dark');
    }

    /**
     * @return array<string, string|int>
     */
    protected static function definition(): array
    {
        return ['Light' => 'light', 'Dark' => 'dark'];
    }
}
