<?php

/*
 * This file is part of the PHP 7.4 port of the official PHP MCP SDK.
 *
 * Generated by bin/port from the Mcp\Schema namespace of mcp/sdk — change the
 * upstream source, or runtime/, and re-run it rather than editing this file.
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Mcp\Schema\Enum;

/**
 * The severity of a log message.
 *
 * These map to syslog message severities, as specified in RFC-5424:
 * https://datatracker.ietf.org/doc/html/rfc5424#section-6.2.1
 *
 * @author Kyrian Obikwelu <koshnawaza@gmail.com>
 *
 * @deprecated since protocol revision 2026-07-28 (SEP-2577), earliest removal 2027-07-28.
 *  Log to stderr (stdio) or use OpenTelemetry instead.
 */
final class LoggingLevel extends BackedEnum
{
    public const Debug = 'debug';
    public const Info = 'info';
    public const Notice = 'notice';
    public const Warning = 'warning';
    public const Error = 'error';
    public const Critical = 'critical';
    public const Alert = 'alert';
    public const Emergency = 'emergency';

    public static function Debug(): self
    {
        return self::case('Debug');
    }

    public static function Info(): self
    {
        return self::case('Info');
    }

    public static function Notice(): self
    {
        return self::case('Notice');
    }

    public static function Warning(): self
    {
        return self::case('Warning');
    }

    public static function Error(): self
    {
        return self::case('Error');
    }

    public static function Critical(): self
    {
        return self::case('Critical');
    }

    public static function Alert(): self
    {
        return self::case('Alert');
    }

    public static function Emergency(): self
    {
        return self::case('Emergency');
    }

    /**
     * @return array<string, string|int>
     */
    protected static function definition(): array
    {
        return ['Debug' => 'debug', 'Info' => 'info', 'Notice' => 'notice', 'Warning' => 'warning', 'Error' => 'error', 'Critical' => 'critical', 'Alert' => 'alert', 'Emergency' => 'emergency'];
    }

    /**
     * RFC 5424 ordering, inverted so a larger number is more severe — which is
     * the direction a minimum-level comparison reads in.
     */
    public function severity(): int
    {
        switch ($this) {
            case self::Debug():
                return 0;
            case self::Info():
                return 1;
            case self::Notice():
                return 2;
            case self::Warning():
                return 3;
            case self::Error():
                return 4;
            case self::Critical():
                return 5;
            case self::Alert():
                return 6;
            case self::Emergency():
                return 7;
        }
    }

    /**
     * Whether a message at this level should be emitted when $minimum was
     * requested.
     */
    public function isAtLeast(self $minimum): bool
    {
        return $this->severity() >= $minimum->severity();
    }
}
