<?php

/*
 * This file is part of the PHP 7.4 port of the official PHP MCP SDK.
 *
 * Generated by bin/port from the Mcp\Schema namespace of mcp/sdk — change the
 * upstream source, or runtime/, and re-run it rather than editing this file.
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Mcp\Schema\Enum;

/**
 * Tells the client how to read a result before it looks at the body.
 *
 * Required from 2026-07-28, where a request may come back finished or asking
 * for input. A client seeing no `resultType` MUST read it as
 * {@see self::Complete}.
 *
 * @author Christopher Hertel <mail@christopher-hertel.de>
 */
final class ResultType extends BackedEnum
{
    /** The request finished; the result holds the final content. */
    public const Complete = 'complete';
    /** The request needs more input before it can finish (MRTR). */
    public const InputRequired = 'input_required';

    public static function Complete(): self
    {
        return self::case('Complete');
    }

    public static function InputRequired(): self
    {
        return self::case('InputRequired');
    }

    /**
     * @return array<string, string|int>
     */
    protected static function definition(): array
    {
        return ['Complete' => 'complete', 'InputRequired' => 'input_required'];
    }
}
