<?php

/*
 * This file is part of the PHP 7.4 port of the official PHP MCP SDK.
 *
 * Generated by bin/port from the Mcp\Schema namespace of mcp/sdk — change the
 * upstream source, or runtime/, and re-run it rather than editing this file.
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Mcp\Schema\Enum;

/**
 * The sender or recipient of messages and data in a conversation.
 *
 * @author Kyrian Obikwelu <koshnawaza@gmail.com>
 */
final class Role extends BackedEnum
{
    public const User = 'user';
    public const Assistant = 'assistant';

    public static function User(): self
    {
        return self::case('User');
    }

    public static function Assistant(): self
    {
        return self::case('Assistant');
    }

    /**
     * @return array<string, string|int>
     */
    protected static function definition(): array
    {
        return ['User' => 'user', 'Assistant' => 'assistant'];
    }
}
