<?php

/*
 * This file is part of the PHP 7.4 port of the official PHP MCP SDK.
 *
 * Generated by bin/port from the Mcp\Schema namespace of mcp/sdk — change the
 * upstream source, or runtime/, and re-run it rather than editing this file.
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Mcp\Schema\Enum;

/**
 * Which servers' context a sampling request asks the client to attach.
 *
 * `thisServer` and `allServers` are themselves deprecated since 2025-11-25
 * (SEP-2596): omit the field or use `none`.
 *
 * @deprecated since protocol revision 2026-07-28 (SEP-2577), earliest removal 2027-07-28.
 *  Integrate with an LLM provider's API directly instead.
 */
final class SamplingContext extends BackedEnum
{
    public const NONE = 'none';
    public const THIS_SERVER = 'thisServer';
    public const ALL_SERVERS = 'allServers';

    public static function NONE(): self
    {
        return self::case('NONE');
    }

    public static function THIS_SERVER(): self
    {
        return self::case('THIS_SERVER');
    }

    public static function ALL_SERVERS(): self
    {
        return self::case('ALL_SERVERS');
    }

    /**
     * @return array<string, string|int>
     */
    protected static function definition(): array
    {
        return ['NONE' => 'none', 'THIS_SERVER' => 'thisServer', 'ALL_SERVERS' => 'allServers'];
    }
}
