<?php

/*
 * This file is part of the PHP 7.4 port of the official PHP MCP SDK.
 *
 * Generated by bin/port from the Mcp\Schema namespace of mcp/sdk — change the
 * upstream source, or runtime/, and re-run it rather than editing this file.
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Mcp\Schema\Enum;

/**
 * How the model may use the tools offered on a sampling request.
 *
 * @deprecated since protocol revision 2026-07-28 (SEP-2577), earliest removal 2027-07-28.
 *  Integrate with an LLM provider's API directly instead.
 */
final class ToolChoiceMode extends BackedEnum
{
    public const Auto = 'auto';
    public const Required = 'required';
    public const None = 'none';

    public static function Auto(): self
    {
        return self::case('Auto');
    }

    public static function Required(): self
    {
        return self::case('Required');
    }

    public static function None(): self
    {
        return self::case('None');
    }

    /**
     * @return array<string, string|int>
     */
    protected static function definition(): array
    {
        return ['Auto' => 'auto', 'Required' => 'required', 'None' => 'none'];
    }
}
