<?php

/*
 * This file is part of the PHP 7.4 port of the official PHP MCP SDK.
 *
 * Generated by bin/port from the Mcp\Schema namespace of mcp/sdk — change the
 * upstream source, or runtime/, and re-run it rather than editing this file.
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Mcp\Tests\Unit\Schema\JsonRpc;

use Mcp\Schema\JsonRpc\Request;
use PHPUnit\Framework\TestCase;

final class RequestTest extends TestCase
{
    public function testMetaAndIdAreLoopedThrough(): void
    {
        $requestImplementation = new class extends Request {
            public static function getMethod(): string
            {
                return 'foo/bar';
            }

            /**
             * @return static
             */
            public static function fromParams(?array $params)
            {
                return new self();
            }

            protected function getParams(): ?array
            {
                return null;
            }
        };

        $notification = $requestImplementation::fromArray([
            'jsonrpc' => '2.0',
            'id' => '12345',
            'method' => 'foo/bar',
            'params' => [
                '_meta' => ['key' => 'value'],
            ],
        ]);

        $expectedMeta = [
            'jsonrpc' => '2.0',
            'id' => '12345',
            'method' => 'foo/bar',
            'params' => [
                '_meta' => ['key' => 'value'],
            ],
        ];

        $this->assertSame($expectedMeta, $notification->jsonSerialize());
    }
}
