<?php

/*
 * This file is part of the PHP 7.4 port of the official PHP MCP SDK.
 *
 * Generated by bin/port from the Mcp\Schema namespace of mcp/sdk — change the
 * upstream source, or runtime/, and re-run it rather than editing this file.
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Mcp\Schema\JsonRpc;

/**
 * Interface for all incoming JSON-RPC messages that should be processed by a handler, and are expected to have a method.
 *
 * @author Christopher Hertel <mail@christopher-hertel.de>
 */
interface HasMethodInterface
{
    public static function getMethod(): string;

    /**
     * @param array<string, mixed> $data
     *
     * @return static
     */
    public static function fromArray(array $data);
}
