<?php

/*
 * This file is part of the PHP 7.4 port of the official PHP MCP SDK.
 *
 * Generated by bin/port from the Mcp\Schema namespace of mcp/sdk — change the
 * upstream source, or runtime/, and re-run it rather than editing this file.
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Mcp\Schema\JsonRpc;

/**
 * Refers to any valid JSON-RPC object that can be decoded off the wire, or encoded to be sent.
 *
 * @author Kyrian Obikwelu <koshnawaza@gmail.com>
 */
interface MessageInterface extends \JsonSerializable
{
    public const JSONRPC_VERSION = '2.0';
    public const PROTOCOL_VERSION = '2025-11-25';
}
