<?php

/*
 * This file is part of the PHP 7.4 port of the official PHP MCP SDK.
 *
 * Generated by bin/port from the Mcp\Schema namespace of mcp/sdk — change the
 * upstream source, or runtime/, and re-run it rather than editing this file.
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Mcp\Schema\JsonRpc;

/**
 * Base class for all specific MCP result objects (the value of the 'result' field).
 *
 * @author Kyrian Obikwelu <koshnawaza@gmail.com>
 */
interface ResultInterface extends \JsonSerializable
{
}
