<?php

/*
 * This file is part of the PHP 7.4 port of the official PHP MCP SDK.
 *
 * Generated by bin/port from the Mcp\Schema namespace of mcp/sdk — change the
 * upstream source, or runtime/, and re-run it rather than editing this file.
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Mcp\Schema\Elicitation;

/**
 * Schema definition for boolean fields in elicitation requests.
 *
 * @author Johannes Wachter <johannes@sulu.io>
 */
final class BooleanSchemaDefinition extends AbstractSchemaDefinition
{
    /**
     * @readonly
     */
    public ?bool $default = null;

    /**
     * @param ?string     $title       Optional human-readable title for the field
     * @param string|null $description Optional description/help text
     * @param bool|null   $default     Optional default value
     */
    public function __construct(
        ?string $title = null,
        ?string $description = null,
        ?bool $default = null
    ) {
        $this->default = $default;
        parent::__construct($title, $description);
    }

    /**
     * @param array{
     *     title?: string,
     *     description?: string,
     *     default?: bool,
     * } $data
     */
    public static function fromArray(array $data): self
    {
        self::validateTitle($data, 'boolean');

        return new self(
            $data['title'] ?? null,
            $data['description'] ?? null,
            isset($data['default']) ? (bool) $data['default'] : null,
        );
    }

    /**
     * @return array{
     *     type: string,
     *     title?: string,
     *     description?: string,
     *     default?: bool,
     * }
     */
    public function jsonSerialize(): array
    {
        $data = $this->buildBaseJson('boolean');

        if (null !== $this->default) {
            $data['default'] = $this->default;
        }

        return $data;
    }
}
