<?php

/*
 * This file is part of the PHP 7.4 port of the official PHP MCP SDK.
 *
 * Generated by bin/port from the Mcp\Schema namespace of mcp/sdk — change the
 * upstream source, or runtime/, and re-run it rather than editing this file.
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Mcp\Schema\Elicitation;

use Mcp\Exception\InvalidArgumentException;

/**
 * Schema wrapper for elicitation requestedSchema (JSON Schema object type).
 *
 * Represents an object schema with primitive property definitions and optional required fields.
 *
 * @author Johannes Wachter <johannes@sulu.io>
 */
final class ElicitationSchema implements \JsonSerializable
{
    /**
     * @var array<string, AbstractSchemaDefinition>
     *
     * @readonly
     */
    public array $properties;
    /**
     * @var string[]
     *
     * @readonly
     */
    public array $required = [];

    /**
     * @param array<string, AbstractSchemaDefinition> $properties Property definitions keyed by name
     * @param string[]                                $required   Array of required property names
     */
    public function __construct(
        array $properties,
        array $required = []
    ) {
        $this->properties = $properties;
        $this->required = $required;
        if ([] === $properties) {
            throw new InvalidArgumentException('properties array must not be empty.');
        }

        foreach ($required as $name) {
            if (!\is_string($name)) {
                throw new InvalidArgumentException('Each entry in "required" must be a string.');
            }
            if (!\array_key_exists($name, $properties)) {
                throw new InvalidArgumentException(\sprintf('Required property "%s" is not defined in properties.', $name));
            }
        }
    }

    /**
     * Create an ElicitationSchema from array data.
     *
     * @param array{
     *     type?: string,
     *     properties: array<string, array{type: string, title: string, ...}>,
     *     required?: string[],
     * } $data
     */
    public static function fromArray(array $data): self
    {
        if (isset($data['type']) && 'object' !== $data['type']) {
            throw new InvalidArgumentException('ElicitationSchema type must be "object".');
        }

        if (!isset($data['properties']) || !\is_array($data['properties'])) {
            throw new InvalidArgumentException('Missing or invalid "properties" for elicitation schema.');
        }

        $properties = [];
        foreach ($data['properties'] as $name => $propertyData) {
            if (!\is_array($propertyData)) {
                throw new InvalidArgumentException(\sprintf('Property "%s" must be an array.', $name));
            }
            $properties[$name] = self::createSchemaDefinition($propertyData);
        }

        if (isset($data['required']) && !\is_array($data['required'])) {
            throw new InvalidArgumentException('Invalid "required" for elicitation schema; expected an array.');
        }

        return new self(
            $properties,
            $data['required'] ?? [],
        );
    }

    /**
     * Create a schema definition from array data.
     *
     * @param array<string, mixed> $data
     */
    private static function createSchemaDefinition(array $data): AbstractSchemaDefinition
    {
        if (!isset($data['type']) || !\is_string($data['type'])) {
            throw new InvalidArgumentException('Missing or invalid "type" for schema definition.');
        }

        switch ($data['type']) {
            case 'string':
                return self::resolveStringType($data);
            case 'integer':
            case 'number':
                return NumberSchemaDefinition::fromArray($data);
            case 'boolean':
                return BooleanSchemaDefinition::fromArray($data);
            case 'array':
                return self::resolveArrayType($data);
            default:
                throw new InvalidArgumentException(\sprintf('Unsupported type "%s". Supported types are: string, integer, number, boolean, array.', $data['type']));
        }
    }

    /**
     * @param array<string, mixed> $data
     */
    private static function resolveStringType(array $data): AbstractSchemaDefinition
    {
        if (isset($data['oneOf'])) {
            return TitledEnumSchemaDefinition::fromArray($data);
        }

        if (isset($data['enum'])) {
            return EnumSchemaDefinition::fromArray($data);
        }

        return StringSchemaDefinition::fromArray($data);
    }

    /**
     * @param array<string, mixed> $data
     */
    private static function resolveArrayType(array $data): AbstractSchemaDefinition
    {
        if (isset($data['items']['anyOf'])) {
            return TitledMultiSelectEnumSchemaDefinition::fromArray($data);
        }

        if (isset($data['items']['enum'])) {
            return MultiSelectEnumSchemaDefinition::fromArray($data);
        }

        throw new InvalidArgumentException('Array type must have "items" with either "enum" or "anyOf".');
    }

    /**
     * @return array{
     *     type: string,
     *     properties: array<string, mixed>,
     *     required?: string[],
     * }
     */
    public function jsonSerialize(): array
    {
        $data = [
            'type' => 'object',
            'properties' => [],
        ];

        foreach ($this->properties as $name => $property) {
            $data['properties'][$name] = $property->jsonSerialize();
        }

        if ([] !== $this->required) {
            $data['required'] = $this->required;
        }

        return $data;
    }
}
