<?php

/*
 * This file is part of the PHP 7.4 port of the official PHP MCP SDK.
 *
 * Generated by bin/port from the Mcp\Schema namespace of mcp/sdk — change the
 * upstream source, or runtime/, and re-run it rather than editing this file.
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Mcp\Schema\Elicitation;

use Mcp\Exception\InvalidArgumentException;

/**
 * Schema definition for string enum fields in elicitation requests.
 *
 * Provides a list of allowed values with optional human-readable labels.
 *
 * @author Johannes Wachter <johannes@sulu.io>
 */
final class EnumSchemaDefinition extends AbstractSchemaDefinition
{
    /**
     * @var string[]
     *
     * @readonly
     */
    public array $enum;
    /**
     * @readonly
     */
    public ?string $default = null;
    /**
     * @var string[]|null
     *
     * @readonly
     */
    public ?array $enumNames = null;

    /**
     * @param ?string       $title       Optional human-readable title for the field
     * @param string[]      $enum        Array of allowed string values
     * @param string|null   $description Optional description/help text
     * @param string|null   $default     Optional default value (must be in enum)
     * @param string[]|null $enumNames   Optional human-readable labels for each enum value
     */
    public function __construct(
        ?string $title,
        array $enum,
        ?string $description = null,
        ?string $default = null,
        ?array $enumNames = null
    ) {
        $this->enum = $enum;
        $this->default = $default;
        $this->enumNames = $enumNames;
        parent::__construct($title, $description);

        if ([] === $enum) {
            throw new InvalidArgumentException('enum array must not be empty.');
        }

        foreach ($enum as $value) {
            if (!\is_string($value)) {
                throw new InvalidArgumentException('All enum values must be strings.');
            }
        }

        if (null !== $enumNames && \count($enumNames) !== \count($enum)) {
            throw new InvalidArgumentException('enumNames length must match enum length.');
        }

        if (null !== $default && !\in_array($default, $enum, true)) {
            throw new InvalidArgumentException(\sprintf('Default value "%s" is not in the enum array.', $default));
        }
    }

    /**
     * @param array{
     *     title?: string,
     *     enum: string[],
     *     description?: string,
     *     default?: string,
     *     enumNames?: string[],
     * } $data
     */
    public static function fromArray(array $data): self
    {
        self::validateTitle($data, 'enum');

        if (!isset($data['enum']) || !\is_array($data['enum'])) {
            throw new InvalidArgumentException('Missing or invalid "enum" for enum schema definition.');
        }

        return new self(
            $data['title'] ?? null,
            $data['enum'],
            $data['description'] ?? null,
            $data['default'] ?? null,
            $data['enumNames'] ?? null,
        );
    }

    /**
     * @return array{
     *     type: string,
     *     title?: string,
     *     enum: string[],
     *     description?: string,
     *     default?: string,
     *     enumNames?: string[],
     * }
     */
    public function jsonSerialize(): array
    {
        $data = ['type' => 'string'];

        if (null !== $this->title) {
            $data['title'] = $this->title;
        }

        $data['enum'] = $this->enum;

        if (null !== $this->description) {
            $data['description'] = $this->description;
        }

        if (null !== $this->default) {
            $data['default'] = $this->default;
        }

        if (null !== $this->enumNames) {
            $data['enumNames'] = $this->enumNames;
        }

        return $data;
    }
}
