<?php

declare(strict_types=1);

use PhpCsFixer\Config;
use PhpCsFixer\Finder;

/*
 * Mirrors the upstream SDK's style so a ported file stays diffable against the
 * one it came from. The @Symfony:risky set stays off: several of its
 * rules rewrite to functions that only exist from PHP 8.0.
 */

$fileHeader = <<<'EOF'
    This file is part of the PHP 7.4 port of the official PHP MCP SDK.

    Generated by bin/port from the Mcp\Schema namespace of mcp/sdk — change the
    upstream source, or runtime/, and re-run it rather than editing this file.

    For the full copyright and license information, please view the LICENSE
    file that was distributed with this source code.
    EOF;

return (new Config())
    ->setRules([
        '@Symfony' => true,
        'header_comment' => ['header' => $fileHeader],
        'php_unit_test_case_static_method_calls' => ['call_type' => 'this'],
        // A trailing comma after the last parameter is PHP 8.0 syntax.
        'trailing_comma_in_multiline' => ['elements' => ['arrays', 'arguments']],
    ])
    ->setRiskyAllowed(true)
    ->setFinder((new Finder())->in(__DIR__ . '/../../build/stage'))
    ->setCacheFile(__DIR__ . '/../../build/php-cs-fixer.cache')
;
