<?php

/*
 * This file is part of the PHP 7.4 port of the official PHP MCP SDK.
 *
 * Generated by bin/port from the Mcp\Schema namespace of mcp/sdk — change the
 * upstream source, or runtime/, and re-run it rather than editing this file.
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Mcp\Schema\Content;

use Mcp\Exception\InvalidArgumentException;
use Mcp\Schema\Enum\Role;

/**
 * Describes a message returned as part of a prompt.
 *
 * @phpstan-import-type TextContentData from TextContent
 * @phpstan-import-type ImageContentData from ImageContent
 * @phpstan-import-type AudioContentData from AudioContent
 * @phpstan-import-type ResourceLinkData from ResourceLink
 * @phpstan-import-type EmbeddedResourceData from EmbeddedResource
 *
 * @phpstan-type PromptMessageData array{
 *     role: string,
 *     content: TextContentData|ImageContentData|AudioContentData|ResourceLinkData|EmbeddedResourceData,
 * }
 *
 * @author Kyrian Obikwelu <koshnawaza@gmail.com>
 */
class PromptMessage extends Content
{
    /**
     * @readonly
     */
    public Role $role;
    /**
     * @var TextContent|ImageContent|AudioContent|ResourceLink|EmbeddedResource
     *
     * @readonly
     */
    public $content;

    /**
     * Create a new PromptMessage instance.
     *
     * @param Role                                                                $role    The role of the message
     * @param TextContent|ImageContent|AudioContent|ResourceLink|EmbeddedResource $content The content of the message
     */
    public function __construct(
        Role $role,
        $content
    ) {
        $this->role = $role;
        $this->content = $content;
        parent::__construct('prompt');
    }

    /**
     * @param PromptMessageData $data
     */
    public static function fromArray(array $data): self
    {
        if (!isset($data['role']) || !\is_string($data['role'])) {
            throw new InvalidArgumentException('Missing or invalid "role" in PromptMessage data.');
        }
        if (!isset($data['content']) || !\is_array($data['content'])) {
            throw new InvalidArgumentException('Missing or invalid "content" in PromptMessage data.');
        }

        $contentData = $data['content'];
        $contentType = $contentData['type'] ?? null;
        if (!\is_string($contentType)) {
            throw new InvalidArgumentException('Missing or invalid content "type" for PromptMessage.');
        }

        switch ($contentType) {
            case 'text':
                $content = TextContent::fromArray($contentData);
                break;
            case 'image':
                $content = ImageContent::fromArray($contentData);
                break;
            case 'audio':
                $content = AudioContent::fromArray($contentData);
                break;
            case 'resource':
                $content = EmbeddedResource::fromArray($contentData);
                break;
            case 'resource_link':
                $content = ResourceLink::fromArray($contentData);
                break;
            default:
                throw new InvalidArgumentException(\sprintf('Invalid content type "%s" for PromptMessage.', $contentType));
        }

        if (null === $role = Role::tryFrom($data['role'])) {
            throw new InvalidArgumentException(\sprintf('Invalid "role" value "%s" in PromptMessage data.', $data['role']));
        }

        return new self($role, $content);
    }

    /**
     * Convert the message to an array.
     *
     * @return array{
     *     role: string,
     *     content: TextContent|ImageContent|AudioContent|ResourceLink|EmbeddedResource
     * }
     */
    public function jsonSerialize(): array
    {
        return [
            'role' => $this->role->value,
            'content' => $this->content,
        ];
    }
}
