<?php

/*
 * This file is part of the PHP 7.4 port of the official PHP MCP SDK.
 *
 * Generated by bin/port from the Mcp\Schema namespace of mcp/sdk — change the
 * upstream source, or runtime/, and re-run it rather than editing this file.
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Mcp\Schema\Content;

use Mcp\Exception\InvalidArgumentException;
use Mcp\Schema\Annotations;
use Mcp\Schema\Icon;

/**
 * Represents a link to a resource, without embedding its contents.
 *
 * A resource that the server is capable of reading, included in a prompt or
 * tool call result. Unlike `EmbeddedResource`, this points to a resource
 * without including its full content, allowing clients to fetch it separately.
 *
 * @phpstan-import-type AnnotationsData from Annotations
 * @phpstan-import-type IconData from Icon
 *
 * @phpstan-type ResourceLinkData array{
 *     type: 'resource_link',
 *     uri: string,
 *     name: string,
 *     title?: string,
 *     description?: string,
 *     mimeType?: string,
 *     annotations?: AnnotationsData,
 *     size?: int,
 *     icons?: IconData[],
 *     _meta?: array<string, mixed>,
 * }
 *
 * @author Alex Rothberg <cancan101@users.noreply.github.com>
 */
class ResourceLink extends Content
{
    /**
     * @readonly
     */
    public string $uri;
    /**
     * @readonly
     */
    public string $name;
    /**
     * @readonly
     */
    public ?string $title = null;
    /**
     * @readonly
     */
    public ?string $description = null;
    /**
     * @readonly
     */
    public ?string $mimeType = null;
    /**
     * @readonly
     */
    public ?Annotations $annotations = null;
    /**
     * @readonly
     */
    public ?int $size = null;
    /**
     * @var ?Icon[]
     *
     * @readonly
     */
    public ?array $icons = null;
    /**
     * @var ?array<string, mixed>
     *
     * @readonly
     */
    public ?array $meta = null;

    /**
     * @param string                $uri         the URI of this resource
     * @param string                $name        a short identifier for this resource
     * @param ?string               $title       optional human-readable title for display in UI
     * @param ?string               $description a description of what this resource represents. This can be used by clients to improve the LLM's understanding of available resources
     * @param ?string               $mimeType    the MIME type of this resource, if known
     * @param ?Annotations          $annotations optional annotations for the client
     * @param ?int                  $size        the size of the raw resource content, in bytes (before base64 encoding or any tokenization), if known
     * @param ?Icon[]               $icons       optional icons representing the resource
     * @param ?array<string, mixed> $meta        optional metadata
     */
    public function __construct(
        string $uri,
        string $name,
        ?string $title = null,
        ?string $description = null,
        ?string $mimeType = null,
        ?Annotations $annotations = null,
        ?int $size = null,
        ?array $icons = null,
        ?array $meta = null
    ) {
        $this->uri = $uri;
        $this->name = $name;
        $this->title = $title;
        $this->description = $description;
        $this->mimeType = $mimeType;
        $this->annotations = $annotations;
        $this->size = $size;
        $this->icons = $icons;
        $this->meta = $meta;
        parent::__construct('resource_link');
    }

    /**
     * @param ResourceLinkData $data
     */
    public static function fromArray(array $data): self
    {
        if (($data['type'] ?? null) !== 'resource_link') {
            throw new InvalidArgumentException('Invalid type for ResourceLink.');
        }
        if (empty($data['uri']) || !\is_string($data['uri'])) {
            throw new InvalidArgumentException('Invalid or missing "uri" in ResourceLink data.');
        }
        if (empty($data['name']) || !\is_string($data['name'])) {
            throw new InvalidArgumentException('Invalid or missing "name" in ResourceLink data.');
        }
        if (isset($data['_meta']) && !\is_array($data['_meta'])) {
            throw new InvalidArgumentException('Invalid "_meta" in ResourceLink data.');
        }
        if (isset($data['description']) && !\is_string($data['description'])) {
            throw new InvalidArgumentException('Invalid "description" in ResourceLink data.');
        }
        if (isset($data['mimeType']) && !\is_string($data['mimeType'])) {
            throw new InvalidArgumentException('Invalid "mimeType" in ResourceLink data.');
        }
        if (isset($data['size']) && !\is_int($data['size'])) {
            throw new InvalidArgumentException('Invalid "size" in ResourceLink data; expected an integer.');
        }

        return new self(
            $data['uri'],
            $data['name'],
            isset($data['title']) && \is_string($data['title']) ? $data['title'] : null,
            $data['description'] ?? null,
            $data['mimeType'] ?? null,
            Annotations::tryFromArray($data['annotations'] ?? null, 'ResourceLink'),
            $data['size'] ?? null,
            isset($data['icons']) && \is_array($data['icons']) ? Icon::listFromArray($data['icons'], 'ResourceLink') : null,
            $data['_meta'] ?? null,
        );
    }

    /**
     * @return array{
     *     type: 'resource_link',
     *     uri: string,
     *     name: string,
     *     title?: string,
     *     description?: string,
     *     mimeType?: string,
     *     annotations?: Annotations,
     *     size?: int,
     *     icons?: Icon[],
     *     _meta?: array<string, mixed>,
     * }
     */
    public function jsonSerialize(): array
    {
        $data = [
            'type' => $this->type,
            'uri' => $this->uri,
            'name' => $this->name,
        ];
        if (null !== $this->title) {
            $data['title'] = $this->title;
        }
        if (null !== $this->description) {
            $data['description'] = $this->description;
        }
        if (null !== $this->mimeType) {
            $data['mimeType'] = $this->mimeType;
        }
        if (null !== $this->annotations) {
            $data['annotations'] = $this->annotations;
        }
        if (null !== $this->size) {
            $data['size'] = $this->size;
        }
        if (null !== $this->icons) {
            $data['icons'] = $this->icons;
        }
        if (null !== $this->meta) {
            $data['_meta'] = $this->meta;
        }

        return $data;
    }
}
