<?php

/*
 * This file is part of the PHP 7.4 port of the official PHP MCP SDK.
 *
 * Generated by bin/port from the Mcp\Schema namespace of mcp/sdk — change the
 * upstream source, or runtime/, and re-run it rather than editing this file.
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Mcp\Schema\Content;

/**
 * The contents of a specific resource or sub-resource.
 *
 * @phpstan-type ResourceContentsData = array{
 *     uri: string,
 *     mimeType?: string|null,
 *     _meta?: array<string, mixed>
 * }
 *
 * @author Kyrian Obikwelu <koshnawaza@gmail.com>
 */
abstract class ResourceContents implements \JsonSerializable
{
    /**
     * @readonly
     */
    public string $uri;
    /**
     * @readonly
     */
    public ?string $mimeType = null;
    /**
     * @var ?array<string, mixed>
     *
     * @readonly
     */
    public ?array $meta = null;

    /**
     * @param string                $uri      the URI of the resource or sub-resource
     * @param string|null           $mimeType the MIME type of the resource or sub-resource
     * @param ?array<string, mixed> $meta     Optional metadata
     */
    public function __construct(string $uri, ?string $mimeType = null, ?array $meta = null)
    {
        $this->uri = $uri;
        $this->mimeType = $mimeType;
        $this->meta = $meta;
    }

    /**
     * @return ResourceContentsData
     */
    public function jsonSerialize(): array
    {
        $data = ['uri' => $this->uri];
        if (null !== $this->mimeType) {
            $data['mimeType'] = $this->mimeType;
        }

        if (null !== $this->meta) {
            $data['_meta'] = $this->meta;
        }

        return $data;
    }
}
