<?php

/*
 * This file is part of the PHP 7.4 port of the official PHP MCP SDK.
 *
 * Generated by bin/port from the Mcp\Schema namespace of mcp/sdk — change the
 * upstream source, or runtime/, and re-run it rather than editing this file.
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Mcp\Schema\Content;

use Mcp\Exception\InvalidArgumentException;
use Mcp\Schema\Annotations;

/**
 * Represents text content in MCP.
 *
 * @phpstan-import-type AnnotationsData from Annotations
 *
 * @phpstan-type TextContentData array{
 *     type: 'text',
 *     text: string,
 *     annotations?: AnnotationsData,
 * }
 *
 * @author Kyrian Obikwelu <koshnawaza@gmail.com>
 */
class TextContent extends Content
{
    public $text;
    /**
     * @readonly
     */
    public ?Annotations $annotations = null;

    /**
     * Create a new TextContent instance from any value.
     *
     * @param mixed        $text        The value to convert to text
     * @param ?Annotations $annotations Optional annotations describing the content
     */
    public function __construct(
        $text,
        ?Annotations $annotations = null
    ) {
        $this->text = $text;
        $this->annotations = $annotations;
        $this->text = (\is_array($text) || \is_object($text))
            ? json_encode($text, \JSON_PRETTY_PRINT) : (string) $text;

        parent::__construct('text');
    }

    /**
     * @param TextContentData $data
     */
    public static function fromArray(array $data): self
    {
        if (!isset($data['text']) || !\is_string($data['text'])) {
            throw new InvalidArgumentException('Missing or invalid "text" in TextContent data.');
        }

        return new self(
            $data['text'],
            Annotations::tryFromArray($data['annotations'] ?? null, 'TextContent'),
        );
    }

    /**
     * Create a new TextContent with markdown formatted code.
     *
     * @param string $code     The code to format
     * @param string $language The language for syntax highlighting
     */
    public static function code(string $code, string $language = '', ?Annotations $annotations = null): self
    {
        return new self("```{$language}\n{$code}\n```", $annotations);
    }

    /**
     * Convert the content to an array.
     *
     * @return array{
     *     type: 'text',
     *     text: string,
     *     annotations?: Annotations,
     * }
     */
    public function jsonSerialize(): array
    {
        $result = [
            'type' => 'text',
            'text' => $this->text,
        ];

        if (null !== $this->annotations) {
            $result['annotations'] = $this->annotations;
        }

        return $result;
    }
}
