<?php

/*
 * This file is part of the PHP 7.4 port of the official PHP MCP SDK.
 *
 * Generated by bin/port from the Mcp\Schema namespace of mcp/sdk — change the
 * upstream source, or runtime/, and re-run it rather than editing this file.
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Mcp\Schema\Content;

use Mcp\Exception\InvalidArgumentException;

/**
 * A request from the assistant to call a tool.
 *
 * @deprecated since protocol revision 2026-07-28 (SEP-2577), earliest removal 2027-07-28.
 *  Integrate with an LLM provider's API directly instead.
 */
final class ToolUseContent extends Content
{
    /**
     * @readonly
     */
    public string $id;
    /**
     * @readonly
     */
    public string $name;
    /**
     * @var array<string, mixed>
     *
     * @readonly
     */
    public array $input;
    /**
     * @var ?array<string, mixed>
     *
     * @readonly
     */
    public ?array $meta = null;

    /**
     * @param array<string, mixed>  $input
     * @param ?array<string, mixed> $meta
     */
    public function __construct(
        string $id,
        string $name,
        array $input,
        ?array $meta = null
    ) {
        $this->id = $id;
        $this->name = $name;
        $this->input = $input;
        $this->meta = $meta;
        $arrayIsListFunction = function (array $array): bool {
            if (function_exists('array_is_list')) {
                return array_is_list($array);
            }
            if ([] === $array) {
                return true;
            }
            $current_key = 0;
            foreach ($array as $key => $noop) {
                if ($key !== $current_key) {
                    return false;
                }
                ++$current_key;
            }

            return true;
        };
        if ([] !== $input && $arrayIsListFunction($input)) {
            throw new InvalidArgumentException('ToolUseContent "input" must be a map of argument names, not a list.');
        }

        parent::__construct('tool_use');
    }

    /**
     * @param array{id?: mixed, name?: mixed, input?: mixed, _meta?: mixed} $data
     */
    public static function fromArray(array $data): self
    {
        if (!isset($data['id']) || !\is_string($data['id'])) {
            throw new InvalidArgumentException('Missing or invalid "id" in ToolUseContent data.');
        }
        if (!isset($data['name']) || !\is_string($data['name'])) {
            throw new InvalidArgumentException('Missing or invalid "name" in ToolUseContent data.');
        }
        if (!isset($data['input']) || !\is_array($data['input'])) {
            throw new InvalidArgumentException('Missing or invalid "input" in ToolUseContent data.');
        }
        if (isset($data['_meta']) && !\is_array($data['_meta'])) {
            throw new InvalidArgumentException('Invalid "_meta" in ToolUseContent data.');
        }

        return new self(
            $data['id'],
            $data['name'],
            $data['input'],
            $data['_meta'] ?? null,
        );
    }

    /**
     * @return array{type: 'tool_use', id: string, name: string, input: array<string, mixed>|\stdClass, _meta?: array<string, mixed>}
     */
    public function jsonSerialize(): array
    {
        $data = [
            'type' => $this->type,
            'id' => $this->id,
            'name' => $this->name,
            'input' => $this->input ?: new \stdClass(),
        ];

        if (null !== $this->meta) {
            $data['_meta'] = $this->meta;
        }

        return $data;
    }
}
