<?php

/*
 * This file is part of the PHP 7.4 port of the official PHP MCP SDK.
 *
 * Generated by bin/port from the Mcp\Schema namespace of mcp/sdk — change the
 * upstream source, or runtime/, and re-run it rather than editing this file.
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Mcp\Schema\Content;

use Mcp\Exception\InvalidArgumentException;

/**
 * The result of a tool use, provided by the user back to the assistant.
 *
 * Carries the same content blocks as a `tools/call` result, so it accepts everything
 * {@see \Mcp\Schema\Result\CallToolResult} does.
 *
 * @phpstan-type ToolResultBlock TextContent|ImageContent|AudioContent|ResourceLink|EmbeddedResource
 *
 * @deprecated since protocol revision 2026-07-28 (SEP-2577), earliest removal 2027-07-28.
 *  Integrate with an LLM provider's API directly instead.
 */
final class ToolResultContent extends Content
{
    /**
     * @readonly
     */
    public string $toolUseId;
    /**
     * @var ?array<string, mixed>
     *
     * @readonly
     */
    public ?array $structuredContent = null;
    /**
     * @readonly
     */
    public bool $isError = false;
    /**
     * @var ?array<string, mixed>
     *
     * @readonly
     */
    public ?array $meta = null;
    /**
     * @var list<ToolResultBlock>
     *
     * @readonly
     */
    public array $content;

    /**
     * @param array<ToolResultBlock> $content           keys are discarded, the property always holds a list
     * @param ?array<string, mixed>  $structuredContent
     * @param ?array<string, mixed>  $meta
     */
    public function __construct(
        string $toolUseId,
        array $content,
        ?array $structuredContent = null,
        bool $isError = false,
        ?array $meta = null
    ) {
        $this->toolUseId = $toolUseId;
        $this->structuredContent = $structuredContent;
        $this->isError = $isError;
        $this->meta = $meta;
        foreach ($content as $item) {
            if (!$item instanceof TextContent && !$item instanceof ImageContent && !$item instanceof AudioContent && !$item instanceof ResourceLink && !$item instanceof EmbeddedResource) {
                throw new InvalidArgumentException('Tool result content must contain standard content blocks.');
            }
        }

        // array_filter() and friends preserve keys, and a keyed array serializes
        // as a JSON object rather than the array the schema requires.
        $this->content = array_values($content);

        parent::__construct('tool_result');
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        if (!isset($data['toolUseId']) || !\is_string($data['toolUseId'])) {
            throw new InvalidArgumentException('Missing or invalid "toolUseId" in ToolResultContent data.');
        }
        if (!isset($data['content']) || !\is_array($data['content'])) {
            throw new InvalidArgumentException('Missing or invalid "content" in ToolResultContent data.');
        }

        $content = [];
        foreach ($data['content'] as $item) {
            if (!\is_array($item)) {
                throw new InvalidArgumentException('Invalid content block in ToolResultContent data.');
            }

            switch ($item['type'] ?? null) {
                case 'text':
                    $content[] = TextContent::fromArray($item);
                    break;
                case 'image':
                    $content[] = ImageContent::fromArray($item);
                    break;
                case 'audio':
                    $content[] = AudioContent::fromArray($item);
                    break;
                case 'resource_link':
                    $content[] = ResourceLink::fromArray($item);
                    break;
                case 'resource':
                    $content[] = EmbeddedResource::fromArray($item);
                    break;
                default:
                    throw new InvalidArgumentException(\sprintf('Unsupported tool result content type "%s".', $item['type'] ?? null));
            }
        }

        return new self(
            $data['toolUseId'],
            $content,
            isset($data['structuredContent']) && \is_array($data['structuredContent']) ? $data['structuredContent'] : null,
            isset($data['isError']) && true === $data['isError'],
            isset($data['_meta']) && \is_array($data['_meta']) ? $data['_meta'] : null,
        );
    }

    /**
     * @return array<string, mixed>
     */
    public function jsonSerialize(): array
    {
        $data = [
            'type' => $this->type,
            'toolUseId' => $this->toolUseId,
            'content' => $this->content,
        ];

        // Optional in the schema with a default of false, so only sent when it is true.
        if ($this->isError) {
            $data['isError'] = true;
        }

        if (null !== $this->structuredContent) {
            $data['structuredContent'] = $this->structuredContent;
        }
        if (null !== $this->meta) {
            $data['_meta'] = $this->meta;
        }

        return $data;
    }
}
