<?php

/*
 * This file is part of the PHP 7.4 port of the official PHP MCP SDK.
 *
 * Generated by bin/port from the Mcp\Schema namespace of mcp/sdk — change the
 * upstream source, or runtime/, and re-run it rather than editing this file.
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Mcp\Schema\Request;

use Mcp\Exception\InvalidArgumentException;
use Mcp\Schema\JsonRpc\Request;

/**
 * Used by the client to invoke a tool provided by the server.
 *
 * @author Kyrian Obikwelu <koshnawaza@gmail.com>
 */
final class CallToolRequest extends Request
{
    /**
     * @readonly
     */
    public string $name;
    /**
     * @var array<string, mixed>
     *
     * @readonly
     */
    public array $arguments;

    /**
     * @param string               $name      the name of the tool to invoke
     * @param array<string, mixed> $arguments the arguments to pass to the tool
     */
    public function __construct(string $name, array $arguments)
    {
        $this->name = $name;
        $this->arguments = $arguments;
    }

    public static function getMethod(): string
    {
        return 'tools/call';
    }

    /**
     * @return static
     */
    protected static function fromParams(?array $params)
    {
        if (!isset($params['name']) || !\is_string($params['name'])) {
            throw new InvalidArgumentException('Missing or invalid "name" parameter for tools/call.');
        }

        $arguments = $params['arguments'] ?? [];

        if ($arguments instanceof \stdClass) {
            $arguments = (array) $arguments;
        }

        if (!\is_array($arguments)) {
            throw new InvalidArgumentException('Parameter "arguments" must be an array.');
        }

        return new self(
            $params['name'],
            $arguments,
        );
    }

    /**
     * @return array{name: string, arguments: array<string, mixed>}
     */
    protected function getParams(): array
    {
        return [
            'name' => $this->name,
            'arguments' => $this->arguments ?: new \stdClass(),
        ];
    }
}
