<?php

/*
 * This file is part of the PHP 7.4 port of the official PHP MCP SDK.
 *
 * Generated by bin/port from the Mcp\Schema namespace of mcp/sdk — change the
 * upstream source, or runtime/, and re-run it rather than editing this file.
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Mcp\Schema\Request;

use Mcp\Exception\InvalidArgumentException;
use Mcp\Schema\JsonRpc\Request;
use Mcp\Schema\PromptReference;
use Mcp\Schema\ResourceReference;

/**
 * A request from the client to the server, to ask for completion options.
 *
 * @author Kyrian Obikwelu <koshnawaza@gmail.com>
 */
final class CompletionCompleteRequest extends Request
{
    /**
     * @var PromptReference|ResourceReference
     *
     * @readonly
     */
    public $ref;
    /**
     * @var array{name: string, value: string}
     *
     * @readonly
     */
    public array $argument;

    /**
     * @param PromptReference|ResourceReference    $ref      the prompt or resource to complete
     * @param array{ name: string, value: string } $argument the argument to complete
     */
    public function __construct($ref, array $argument)
    {
        $this->ref = $ref;
        $this->argument = $argument;
    }

    public static function getMethod(): string
    {
        return 'completion/complete';
    }

    /**
     * @return static
     */
    protected static function fromParams(?array $params)
    {
        if (!isset($params['ref']) || !\is_array($params['ref'])) {
            throw new InvalidArgumentException('Missing or invalid "ref" parameter for completion/complete.');
        }

        switch ($params['ref']['type'] ?? null) {
            case 'ref/prompt':
                $ref = new PromptReference(self::refString($params['ref'], 'name'));
                break;
            case 'ref/resource':
                $ref = new ResourceReference(self::refString($params['ref'], 'uri'));
                break;
            default:
                throw new InvalidArgumentException('Invalid "ref" parameter for completion/complete.');
        }

        if (!isset($params['argument']) || !\is_array($params['argument'])) {
            throw new InvalidArgumentException('Missing or invalid "argument" parameter for completion/complete.');
        }

        return new self($ref, $params['argument']);
    }

    /**
     * @param array<mixed> $ref
     */
    private static function refString(array $ref, string $key): string
    {
        if (!isset($ref[$key]) || !\is_string($ref[$key])) {
            throw new InvalidArgumentException(\sprintf('Missing or invalid "ref.%s" parameter for completion/complete.', $key));
        }

        return $ref[$key];
    }

    /**
     * @return array{
     *     ref: PromptReference|ResourceReference,
     *     argument: array{ name: string, value: string }
     * }
     */
    protected function getParams(): array
    {
        return [
            'ref' => $this->ref,
            'argument' => $this->argument,
        ];
    }
}
