<?php

/*
 * This file is part of the PHP 7.4 port of the official PHP MCP SDK.
 *
 * Generated by bin/port from the Mcp\Schema namespace of mcp/sdk — change the
 * upstream source, or runtime/, and re-run it rather than editing this file.
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Mcp\Schema\Request;

use Mcp\Exception\InvalidArgumentException;
use Mcp\Schema\JsonRpc\Request;

/**
 * Used by the client to get a prompt provided by the server.
 *
 * @author Kyrian Obikwelu <koshnawaza@gmail.com>
 */
final class GetPromptRequest extends Request
{
    /**
     * @readonly
     */
    public string $name;
    /**
     * @var array<string, string>|null
     *
     * @readonly
     */
    public ?array $arguments = null;

    /**
     * @param string                     $name      the name of the prompt to get
     * @param array<string, string>|null $arguments the arguments to pass to the prompt
     */
    public function __construct(string $name, ?array $arguments = null)
    {
        $this->name = $name;
        $this->arguments = $arguments;
    }

    public static function getMethod(): string
    {
        return 'prompts/get';
    }

    /**
     * @return static
     */
    protected static function fromParams(?array $params)
    {
        if (!isset($params['name']) || !\is_string($params['name']) || empty($params['name'])) {
            throw new InvalidArgumentException('Missing or invalid "name" parameter for prompts/get.');
        }

        $arguments = $params['arguments'] ?? null;
        if (null !== $arguments) {
            if ($arguments instanceof \stdClass) {
                $arguments = (array) $arguments;
            }
            if (!\is_array($arguments)) {
                throw new InvalidArgumentException('Parameter "arguments" must be an array for prompts/get.');
            }
        }

        return new self($params['name'], $arguments);
    }

    /**
     * @return array{name: string, arguments?: array<string, string>}
     */
    protected function getParams(): array
    {
        $params = ['name' => $this->name];

        if (null !== $this->arguments) {
            $params['arguments'] = $this->arguments;
        }

        return $params;
    }
}
