<?php

/*
 * This file is part of the PHP 7.4 port of the official PHP MCP SDK.
 *
 * Generated by bin/port from the Mcp\Schema namespace of mcp/sdk — change the
 * upstream source, or runtime/, and re-run it rather than editing this file.
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Mcp\Schema\Request;

use Mcp\Exception\InvalidArgumentException;
use Mcp\Schema\ClientCapabilities;
use Mcp\Schema\Implementation;
use Mcp\Schema\JsonRpc\Request;

/**
 * This request is sent from the client to the server when it first connects, asking it to begin initialization.
 *
 * @author Kyrian Obikwelu <koshnawaza@gmail.com>
 */
final class InitializeRequest extends Request
{
    /**
     * @readonly
     */
    public string $protocolVersion;
    /**
     * @readonly
     */
    public ClientCapabilities $capabilities;
    /**
     * @readonly
     */
    public Implementation $clientInfo;

    /**
     * @param string             $protocolVersion The latest version of the Model Context Protocol that the client supports. The client MAY decide to support older versions as well.
     * @param ClientCapabilities $capabilities    the capabilities of the client
     * @param Implementation     $clientInfo      information about the client
     */
    public function __construct(string $protocolVersion, ClientCapabilities $capabilities, Implementation $clientInfo)
    {
        $this->protocolVersion = $protocolVersion;
        $this->capabilities = $capabilities;
        $this->clientInfo = $clientInfo;
    }

    public static function getMethod(): string
    {
        return 'initialize';
    }

    /**
     * @return static
     */
    protected static function fromParams(?array $params)
    {
        if (!isset($params['protocolVersion']) || !\is_string($params['protocolVersion'])) {
            throw new InvalidArgumentException('Missing or invalid "protocolVersion" parameter for initialize.');
        }

        if (!isset($params['capabilities']) || !\is_array($params['capabilities'])) {
            throw new InvalidArgumentException('Missing or invalid "capabilities" parameter for initialize.');
        }
        $capabilities = ClientCapabilities::fromArray($params['capabilities']);

        if (!isset($params['clientInfo']) || !\is_array($params['clientInfo'])) {
            throw new InvalidArgumentException('Missing or invalid "clientInfo" parameter for initialize.');
        }
        $clientInfo = Implementation::fromArray($params['clientInfo']);

        return new self($params['protocolVersion'], $capabilities, $clientInfo);
    }

    /**
     * @return array{protocolVersion: string, capabilities: ClientCapabilities, clientInfo: Implementation}
     */
    protected function getParams(): array
    {
        return [
            'protocolVersion' => $this->protocolVersion,
            'capabilities' => $this->capabilities,
            'clientInfo' => $this->clientInfo,
        ];
    }
}
