<?php

/*
 * This file is part of the PHP 7.4 port of the official PHP MCP SDK.
 *
 * Generated by bin/port from the Mcp\Schema namespace of mcp/sdk — change the
 * upstream source, or runtime/, and re-run it rather than editing this file.
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Mcp\Schema\Request;

use Mcp\Exception\InvalidArgumentException;
use Mcp\Schema\JsonRpc\Request;

/**
 * Sent from the client to request a list of tools the server has.
 *
 * @author Kyrian Obikwelu <koshnawaza@gmail.com>
 */
final class ListToolsRequest extends Request
{
    /**
     * @readonly
     */
    public ?string $cursor = null;

    /**
     * @param string|null $cursor An opaque token representing the current pagination position.
     *
     * If provided, the server should return results starting after this cursor.
     */
    public function __construct(?string $cursor = null)
    {
        $this->cursor = $cursor;
    }

    public static function getMethod(): string
    {
        return 'tools/list';
    }

    /**
     * @return static
     */
    protected static function fromParams(?array $params)
    {
        if (isset($params['cursor']) && !\is_string($params['cursor'])) {
            throw new InvalidArgumentException('Invalid "cursor" parameter for tools/list.');
        }

        return new self($params['cursor'] ?? null);
    }

    /**
     * @return array{cursor:string}|null
     */
    protected function getParams(): ?array
    {
        $params = [];
        if (null !== $this->cursor) {
            $params['cursor'] = $this->cursor;
        }

        return $params ?: null;
    }
}
