<?php

/*
 * This file is part of the PHP 7.4 port of the official PHP MCP SDK.
 *
 * Generated by bin/port from the Mcp\Schema namespace of mcp/sdk — change the
 * upstream source, or runtime/, and re-run it rather than editing this file.
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Mcp\Schema\Request;

use Mcp\Schema\JsonRpc\Request;

/**
 * A ping, issued by either the server or the client, to check that the other party is still alive. The receiver must
 * promptly respond, or else may be disconnected.
 *
 * @author Kyrian Obikwelu <koshnawaza@gmail.com>
 */
final class PingRequest extends Request
{
    public static function getMethod(): string
    {
        return 'ping';
    }

    /**
     * @return static
     */
    protected static function fromParams(?array $params)
    {
        return new self();
    }

    protected function getParams(): ?array
    {
        return null;
    }
}
