<?php

/*
 * This file is part of the PHP 7.4 port of the official PHP MCP SDK.
 *
 * Generated by bin/port from the Mcp\Schema namespace of mcp/sdk — change the
 * upstream source, or runtime/, and re-run it rather than editing this file.
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Mcp\Schema\Request;

use Mcp\Exception\InvalidArgumentException;
use Mcp\Schema\JsonRpc\Request;

/**
 * Sent from the client to the server, to read a specific resource URI.
 *
 * @author Kyrian Obikwelu <koshnawaza@gmail.com>
 */
final class ReadResourceRequest extends Request
{
    /**
     * @var non-empty-string
     *
     * @readonly
     */
    public string $uri;

    /**
     * @param non-empty-string $uri the URI of the resource to read
     */
    public function __construct(string $uri)
    {
        $this->uri = $uri;
    }

    public static function getMethod(): string
    {
        return 'resources/read';
    }

    /**
     * @return static
     */
    protected static function fromParams(?array $params)
    {
        if (!isset($params['uri']) || !\is_string($params['uri']) || empty($params['uri'])) {
            throw new InvalidArgumentException('Missing or invalid "uri" parameter for resources/read.');
        }

        return new self($params['uri']);
    }

    /**
     * @return array{uri: non-empty-string}
     */
    protected function getParams(): array
    {
        return [
            'uri' => $this->uri,
        ];
    }
}
