<?php

/*
 * This file is part of the PHP 7.4 port of the official PHP MCP SDK.
 *
 * Generated by bin/port from the Mcp\Schema namespace of mcp/sdk — change the
 * upstream source, or runtime/, and re-run it rather than editing this file.
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Mcp\Schema;

/**
 * @phpstan-type PageItem Tool|Prompt|ResourceTemplate|ResourceDefinition
 *
 * @extends \ArrayObject<int|string, PageItem>
 */
final class Page extends \ArrayObject
{
    /**
     * @var array<int|string, PageItem>
     *
     * @readonly
     */
    public array $references;
    /**
     * @readonly
     */
    public ?string $nextCursor;

    /**
     * @param array<int|string, PageItem> $references Items can be Tool, Prompt, ResourceTemplate, or ResourceDefinition
     */
    public function __construct(
        array $references,
        ?string $nextCursor
    ) {
        $this->references = $references;
        $this->nextCursor = $nextCursor;
        parent::__construct($references, \ArrayObject::ARRAY_AS_PROPS);
    }

    public function count(): int
    {
        return \count($this->references);
    }
}
