<?php

/*
 * This file is part of the PHP 7.4 port of the official PHP MCP SDK.
 *
 * Generated by bin/port from the Mcp\Schema namespace of mcp/sdk — change the
 * upstream source, or runtime/, and re-run it rather than editing this file.
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Mcp\Schema;

use Mcp\Exception\InvalidArgumentException;

/**
 * A prompt or prompt template that the server offers.
 *
 * @phpstan-import-type PromptArgumentData from PromptArgument
 * @phpstan-import-type IconData from Icon
 *
 * @phpstan-type PromptData array{
 *     name: string,
 *     title?: string,
 *     description?: string,
 *     arguments?: PromptArgumentData[],
 *     icons?: IconData[],
 *     _meta?: array<string, mixed>
 * }
 *
 * @author Kyrian Obikwelu <koshnawaza@gmail.com>
 */
class Prompt implements \JsonSerializable
{
    /**
     * @readonly
     */
    public string $name;
    /**
     * @readonly
     */
    public ?string $title = null;
    /**
     * @readonly
     */
    public ?string $description = null;
    /**
     * @var ?PromptArgument[]
     *
     * @readonly
     */
    public ?array $arguments = null;
    /**
     * @var ?Icon[]
     *
     * @readonly
     */
    public ?array $icons = null;
    /**
     * @var ?array<string, mixed>
     *
     * @readonly
     */
    public ?array $meta = null;

    /**
     * @param string                $name        the name of the prompt or prompt template
     * @param ?string               $title       Optional human-readable title for display in UI
     * @param ?string               $description an optional description of what this prompt provides
     * @param ?PromptArgument[]     $arguments   A list of arguments for templating. Null if not a template.
     * @param ?Icon[]               $icons       optional icons representing the prompt
     * @param ?array<string, mixed> $meta        Optional metadata
     */
    public function __construct(
        string $name,
        ?string $title = null,
        ?string $description = null,
        ?array $arguments = null,
        ?array $icons = null,
        ?array $meta = null
    ) {
        $this->name = $name;
        $this->title = $title;
        $this->description = $description;
        $this->arguments = $arguments;
        $this->icons = $icons;
        $this->meta = $meta;
        if (null !== $this->arguments) {
            foreach ($this->arguments as $arg) {
                if (!$arg instanceof PromptArgument) {
                    throw new InvalidArgumentException('All items in Prompt "arguments" must be PromptArgument instances.');
                }
            }
        }
    }

    /**
     * @param PromptData $data
     */
    public static function fromArray(array $data): self
    {
        if (empty($data['name']) || !\is_string($data['name'])) {
            throw new InvalidArgumentException('Invalid or missing "name" in Prompt data.');
        }
        $arguments = null;
        if (isset($data['arguments']) && \is_array($data['arguments'])) {
            $arguments = array_map(
                static function ($argData): PromptArgument {
                    if (!\is_array($argData)) {
                        throw new InvalidArgumentException('Each entry in "arguments" of Prompt data must be an array.');
                    }

                    return PromptArgument::fromArray($argData);
                },
                $data['arguments'],
            );
        }

        if (isset($data['_meta']) && !\is_array($data['_meta'])) {
            throw new InvalidArgumentException('Invalid "_meta" in Prompt data.');
        }
        if (isset($data['title']) && !\is_string($data['title'])) {
            throw new InvalidArgumentException('Invalid "title" in Prompt data.');
        }
        if (isset($data['description']) && !\is_string($data['description'])) {
            throw new InvalidArgumentException('Invalid "description" in Prompt data.');
        }

        return new self(
            $data['name'],
            $data['title'] ?? null,
            $data['description'] ?? null,
            $arguments,
            isset($data['icons']) && \is_array($data['icons']) ? Icon::listFromArray($data['icons'], 'Prompt') : null,
            isset($data['_meta']) ? $data['_meta'] : null,
        );
    }

    /**
     * @return array{
     *     name: string,
     *     title?: string,
     *     description?: string,
     *     arguments?: array<PromptArgument>,
     *     icons?: Icon[],
     *     _meta?: array<string, mixed>
     * }
     */
    public function jsonSerialize(): array
    {
        $data = ['name' => $this->name];
        if (null !== $this->title) {
            $data['title'] = $this->title;
        }
        if (null !== $this->description) {
            $data['description'] = $this->description;
        }
        if (null !== $this->arguments) {
            $data['arguments'] = $this->arguments;
        }
        if (null !== $this->icons) {
            $data['icons'] = $this->icons;
        }
        if (null !== $this->meta) {
            $data['_meta'] = $this->meta;
        }

        return $data;
    }
}
