<?php

/*
 * This file is part of the PHP 7.4 port of the official PHP MCP SDK.
 *
 * Generated by bin/port from the Mcp\Schema namespace of mcp/sdk — change the
 * upstream source, or runtime/, and re-run it rather than editing this file.
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Mcp\Schema;

use Mcp\Exception\InvalidArgumentException;

/**
 * Describes an argument that a prompt can accept.
 *
 * @phpstan-type PromptArgumentData array{
 *     name: string,
 *     description?: string,
 *     required?: bool,
 * }
 *
 * @author Kyrian Obikwelu <koshnawaza@gmail.com>
 */
class PromptArgument implements \JsonSerializable
{
    /**
     * @readonly
     */
    public string $name;
    /**
     * @readonly
     */
    public ?string $description = null;
    /**
     * @readonly
     */
    public ?bool $required = null;

    /**
     * @param string      $name        the name of the argument
     * @param string|null $description a human-readable description of the argument
     * @param bool|null   $required    Whether this argument must be provided. Defaults to false per MCP spec if omitted.
     */
    public function __construct(string $name, ?string $description = null, ?bool $required = null)
    {
        $this->name = $name;
        $this->description = $description;
        $this->required = $required;
    }

    /**
     * @param PromptArgumentData $data
     */
    public static function fromArray(array $data): self
    {
        if (empty($data['name']) || !\is_string($data['name'])) {
            throw new InvalidArgumentException('Invalid or missing "name" in PromptArgument data.');
        }

        if (isset($data['description']) && !\is_string($data['description'])) {
            throw new InvalidArgumentException('Invalid "description" in PromptArgument data.');
        }
        if (isset($data['required']) && !\is_bool($data['required'])) {
            throw new InvalidArgumentException('Invalid "required" in PromptArgument data.');
        }

        return new self(
            $data['name'],
            $data['description'] ?? null,
            $data['required'] ?? null, // Keep null if not present, MCP implies default false
        );
    }

    /**
     * @return PromptArgumentData
     */
    public function jsonSerialize(): array
    {
        $data = ['name' => $this->name];
        if (null !== $this->description) {
            $data['description'] = $this->description;
        }
        if (null !== $this->required) {
            $data['required'] = $this->required;
        }

        return $data;
    }
}
