<?php

/*
 * This file is part of the PHP 7.4 port of the official PHP MCP SDK.
 *
 * Generated by bin/port from the Mcp\Schema namespace of mcp/sdk — change the
 * upstream source, or runtime/, and re-run it rather than editing this file.
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Mcp\Schema;

/**
 * Identifies a prompt.
 *
 * @author Kyrian Obikwelu <koshnawaza@gmail.com>
 */
class PromptReference implements \JsonSerializable
{
    /**
     * @readonly
     */
    public string $name;
    public string $type = 'ref/prompt';

    /**
     * @param string $name The name of the prompt or prompt template
     */
    public function __construct(string $name)
    {
        $this->name = $name;
    }

    /**
     * @return array{
     *     type: string,
     *     name: string,
     * }
     */
    public function jsonSerialize(): array
    {
        return [
            'type' => $this->type,
            'name' => $this->name,
        ];
    }
}
