<?php

/*
 * This file is part of the PHP 7.4 port of the official PHP MCP SDK.
 *
 * Generated by bin/port from the Mcp\Schema namespace of mcp/sdk — change the
 * upstream source, or runtime/, and re-run it rather than editing this file.
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Mcp\Schema;

/**
 * A reference to a resource or resource template definition.
 *
 * @author Kyrian Obikwelu <koshnawaza@gmail.com>
 */
class ResourceReference implements \JsonSerializable
{
    /**
     * @readonly
     */
    public string $uri;
    public string $type = 'ref/resource';

    /**
     * @param string $uri the URI or URI template of the resource
     */
    public function __construct(string $uri)
    {
        $this->uri = $uri;
    }

    /**
     * @return array{
     *     type: string,
     *     uri: string,
     * }
     */
    public function jsonSerialize(): array
    {
        return [
            'type' => $this->type,
            'uri' => $this->uri,
        ];
    }
}
