<?php

/*
 * This file is part of the PHP 7.4 port of the official PHP MCP SDK.
 *
 * Generated by bin/port from the Mcp\Schema namespace of mcp/sdk — change the
 * upstream source, or runtime/, and re-run it rather than editing this file.
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Mcp\Schema;

use Mcp\Exception\InvalidArgumentException;

/**
 * A template description for resources available on the server.
 *
 * @phpstan-import-type AnnotationsData from Annotations
 *
 * @phpstan-type ResourceTemplateData array{
 *     uriTemplate: string,
 *     name: string,
 *     title?: string,
 *     description?: string|null,
 *     mimeType?: string|null,
 *     annotations?: AnnotationsData|null,
 *     _meta?: array<string, mixed>
 * }
 *
 * @author Kyrian Obikwelu <koshnawaza@gmail.com>
 */
class ResourceTemplate implements \JsonSerializable
{
    /**
     * @readonly
     */
    public string $uriTemplate;
    /**
     * @readonly
     */
    public string $name;
    /**
     * @readonly
     */
    public ?string $title = null;
    /**
     * @readonly
     */
    public ?string $description = null;
    /**
     * @readonly
     */
    public ?string $mimeType = null;
    /**
     * @readonly
     */
    public ?Annotations $annotations = null;
    /**
     * @var ?array<string, mixed>
     *
     * @readonly
     */
    public ?array $meta = null;
    /**
     * URI Template pattern regex - requires a valid scheme followed by colon and path with at least one placeholder (RFC 3986).
     * Example patterns: file://{path}/contents.txt, db://{table}/{id}, config:{key}, etc.
     */
    private const URI_TEMPLATE_PATTERN = '/^[a-zA-Z][a-zA-Z0-9+.-]*:.*{[^{}]+}.*/';

    /**
     * @param string                $uriTemplate a URI template (according to RFC 6570) that can be used to construct resource URIs
     * @param string                $name        a short identifier for this resource template type
     * @param ?string               $title       optional human-readable title for display in UI
     * @param ?string               $description a description to help the LLM understand available resources
     * @param ?string               $mimeType    the MIME type for all resources that match this template, if uniform
     * @param ?Annotations          $annotations optional annotations for the client
     * @param ?array<string, mixed> $meta        optional metadata
     */
    public function __construct(
        string $uriTemplate,
        string $name,
        ?string $title = null,
        ?string $description = null,
        ?string $mimeType = null,
        ?Annotations $annotations = null,
        ?array $meta = null
    ) {
        $this->uriTemplate = $uriTemplate;
        $this->name = $name;
        $this->title = $title;
        $this->description = $description;
        $this->mimeType = $mimeType;
        $this->annotations = $annotations;
        $this->meta = $meta;
        if (!preg_match(self::URI_TEMPLATE_PATTERN, $uriTemplate)) {
            throw new InvalidArgumentException(\sprintf('Invalid URI template : "%s" must be a valid URI template with at least one placeholder.', $uriTemplate));
        }
    }

    /**
     * @param ResourceTemplateData $data
     */
    public static function fromArray(array $data): self
    {
        if (empty($data['uriTemplate']) || !\is_string($data['uriTemplate'])) {
            throw new InvalidArgumentException('Invalid or missing "uriTemplate" in ResourceTemplate data.');
        }
        if (empty($data['name']) || !\is_string($data['name'])) {
            throw new InvalidArgumentException('Invalid or missing "name" in ResourceTemplate data.');
        }

        if (isset($data['_meta']) && !\is_array($data['_meta'])) {
            throw new InvalidArgumentException('Invalid "_meta" in ResourceTemplate data.');
        }
        if (isset($data['description']) && !\is_string($data['description'])) {
            throw new InvalidArgumentException('Invalid "description" in ResourceTemplate data.');
        }
        if (isset($data['mimeType']) && !\is_string($data['mimeType'])) {
            throw new InvalidArgumentException('Invalid "mimeType" in ResourceTemplate data.');
        }

        return new self(
            $data['uriTemplate'],
            $data['name'],
            isset($data['title']) && \is_string($data['title']) ? $data['title'] : null,
            $data['description'] ?? null,
            $data['mimeType'] ?? null,
            Annotations::tryFromArray($data['annotations'] ?? null, 'ResourceTemplate'),
            isset($data['_meta']) ? $data['_meta'] : null,
        );
    }

    /**
     * @return array{
     *     uriTemplate: string,
     *     name: string,
     *     title?: string,
     *     description?: string,
     *     mimeType?: string,
     *     annotations?: Annotations,
     *     _meta?: array<string, mixed>
     * }
     */
    public function jsonSerialize(): array
    {
        $data = [
            'uriTemplate' => $this->uriTemplate,
            'name' => $this->name,
        ];
        if (null !== $this->title) {
            $data['title'] = $this->title;
        }
        if (null !== $this->description) {
            $data['description'] = $this->description;
        }
        if (null !== $this->mimeType) {
            $data['mimeType'] = $this->mimeType;
        }
        if (null !== $this->annotations) {
            $data['annotations'] = $this->annotations;
        }
        if (null !== $this->meta) {
            $data['_meta'] = $this->meta;
        }

        return $data;
    }
}
