<?php

/*
 * This file is part of the PHP 7.4 port of the official PHP MCP SDK.
 *
 * Generated by bin/port from the Mcp\Schema namespace of mcp/sdk — change the
 * upstream source, or runtime/, and re-run it rather than editing this file.
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Mcp\Schema;

/**
 * Capabilities that a server may support. Known capabilities are defined here, in this schema, but this is not a closed
 * set: any server can define its own, additional capabilities.
 *
 * @author Kyrian Obikwelu <koshnawaza@gmail.com>
 */
class ServerCapabilities implements \JsonSerializable
{
    /**
     * @readonly
     */
    public ?bool $tools = true;
    /**
     * @readonly
     */
    public ?bool $toolsListChanged = false;
    /**
     * @readonly
     */
    public ?bool $resources = true;
    /**
     * @readonly
     */
    public ?bool $resourcesSubscribe = false;
    /**
     * @readonly
     */
    public ?bool $resourcesListChanged = false;
    /**
     * @readonly
     */
    public ?bool $prompts = true;
    /**
     * @readonly
     */
    public ?bool $promptsListChanged = false;
    /**
     * @readonly
     */
    public ?bool $logging = false;
    /**
     * @readonly
     */
    public ?bool $completions = false;
    /**
     * @var ?array<string, mixed>
     *
     * @readonly
     */
    public ?array $experimental = null;
    /**
     * @var ?array<string, mixed>
     *
     * @readonly
     */
    public ?array $extensions = null;

    /**
     * @param ?bool                 $tools                server exposes callable tools
     * @param ?bool                 $toolsListChanged     server supports list changed notifications for tools
     * @param ?bool                 $resources            server provides readable resources
     * @param ?bool                 $resourcesSubscribe   server supports subscribing to changes in the list of resources
     * @param ?bool                 $resourcesListChanged server supports list changed notifications for resources
     * @param ?bool                 $prompts              server provides prompts templates
     * @param ?bool                 $promptsListChanged   server supports list changed notifications for prompts
     * @param ?bool                 $logging              server emits structured log messages
     * @param ?bool                 $completions          Server supports argument autocompletion
     * @param ?array<string, mixed> $experimental         experimental, non-standard features that the server supports
     * @param ?array<string, mixed> $extensions           protocol extensions the server supports (e.g. io.modelcontextprotocol/ui)
     */
    public function __construct(?bool $tools = true, ?bool $toolsListChanged = false, ?bool $resources = true, ?bool $resourcesSubscribe = false, ?bool $resourcesListChanged = false, ?bool $prompts = true, ?bool $promptsListChanged = false, ?bool $logging = false, ?bool $completions = false, ?array $experimental = null, ?array $extensions = null)
    {
        $this->tools = $tools;
        $this->toolsListChanged = $toolsListChanged;
        $this->resources = $resources;
        $this->resourcesSubscribe = $resourcesSubscribe;
        $this->resourcesListChanged = $resourcesListChanged;
        $this->prompts = $prompts;
        $this->promptsListChanged = $promptsListChanged;
        $this->logging = $logging;
        $this->completions = $completions;
        $this->experimental = $experimental;
        $this->extensions = $extensions;
    }

    /**
     * @param array{
     *     logging?: mixed,
     *     completions?: mixed,
     *     prompts?: array{listChanged?: bool}|object,
     *     resources?: array{listChanged?: bool, subscribe?: bool}|object,
     *     tools?: object|array{listChanged?: bool},
     *     experimental?: array<string, mixed>,
     *     extensions?: array<string, mixed>,
     * } $data
     */
    public static function fromArray(array $data): self
    {
        $loggingEnabled = isset($data['logging']);
        $completionsEnabled = isset($data['completions']);
        $toolsEnabled = isset($data['tools']);
        $promptsEnabled = isset($data['prompts']);
        $resourcesEnabled = isset($data['resources']);

        $promptsListChanged = null;
        if (isset($data['prompts'])) {
            if (\is_array($data['prompts']) && \array_key_exists('listChanged', $data['prompts'])) {
                $promptsListChanged = (bool) $data['prompts']['listChanged'];
            } elseif (\is_object($data['prompts']) && property_exists($data['prompts'], 'listChanged')) {
                $promptsListChanged = (bool) $data['prompts']->listChanged;
            }
        }

        $resourcesSubscribe = null;
        $resourcesListChanged = null;
        if (isset($data['resources'])) {
            if (\is_array($data['resources']) && \array_key_exists('subscribe', $data['resources'])) {
                $resourcesSubscribe = (bool) $data['resources']['subscribe'];
            } elseif (\is_object($data['resources']) && property_exists($data['resources'], 'subscribe')) {
                $resourcesSubscribe = (bool) $data['resources']->subscribe;
            }
            if (\is_array($data['resources']) && \array_key_exists('listChanged', $data['resources'])) {
                $resourcesListChanged = (bool) $data['resources']['listChanged'];
            } elseif (\is_object($data['resources']) && property_exists($data['resources'], 'listChanged')) {
                $resourcesListChanged = (bool) $data['resources']->listChanged;
            }
        }

        $toolsListChanged = null;
        if (isset($data['tools'])) {
            if (\is_array($data['tools']) && \array_key_exists('listChanged', $data['tools'])) {
                $toolsListChanged = (bool) $data['tools']['listChanged'];
            } elseif (\is_object($data['tools']) && property_exists($data['tools'], 'listChanged')) {
                $toolsListChanged = (bool) $data['tools']->listChanged;
            }
        }

        return new self(
            $toolsEnabled,
            $toolsListChanged,
            $resourcesEnabled,
            $resourcesSubscribe,
            $resourcesListChanged,
            $promptsEnabled,
            $promptsListChanged,
            $loggingEnabled,
            $completionsEnabled,
            \is_array($data['experimental'] ?? null) ? $data['experimental'] : null,
            \is_array($data['extensions'] ?? null) ? $data['extensions'] : null,
        );
    }

    /**
     * Returns a copy with the given protocol extensions merged into the existing ones.
     *
     * Entries in $extensions override existing ones sharing the same id.
     *
     * @param array<string, array<string, mixed>> $extensions
     */
    public function withExtensions(array $extensions): self
    {
        return new self(
            $this->tools,
            $this->toolsListChanged,
            $this->resources,
            $this->resourcesSubscribe,
            $this->resourcesListChanged,
            $this->prompts,
            $this->promptsListChanged,
            $this->logging,
            $this->completions,
            $this->experimental,
            array_merge($this->extensions ?? [], $extensions),
        );
    }

    /**
     * @return array{
     *     logging?: object,
     *     completions?: object,
     *     prompts?: object,
     *     resources?: object,
     *     tools?: object,
     *     experimental?: object,
     *     extensions?: object,
     * }
     */
    public function jsonSerialize(): array
    {
        $data = [];

        if ($this->logging) {
            $data['logging'] = new \stdClass();
        }
        if ($this->completions) {
            $data['completions'] = new \stdClass();
        }

        if ($this->prompts || $this->promptsListChanged) {
            $data['prompts'] = new \stdClass();
            if ($this->promptsListChanged) {
                $data['prompts']->listChanged = $this->promptsListChanged;
            }
        }

        if ($this->resources || $this->resourcesSubscribe || $this->resourcesListChanged) {
            $data['resources'] = new \stdClass();
            if ($this->resourcesSubscribe) {
                $data['resources']->subscribe = $this->resourcesSubscribe;
            }
            if ($this->resourcesListChanged) {
                $data['resources']->listChanged = $this->resourcesListChanged;
            }
        }

        if ($this->tools || $this->toolsListChanged) {
            $data['tools'] = new \stdClass();
            if ($this->toolsListChanged) {
                $data['tools']->listChanged = $this->toolsListChanged;
            }
        }

        if ($this->experimental) {
            $data['experimental'] = (object) $this->experimental;
        }

        if ($this->extensions) {
            // Each entry is a settings *object*; an extension with no settings
            // declares `{}`, and an empty PHP array would serialize as `[]`.
            $data['extensions'] = (object) array_map(
                static fn ($settings) => \is_array($settings) ? (object) $settings : $settings,
                $this->extensions,
            );
        }

        return $data;
    }
}
