<?php

/*
 * This file is part of the PHP 7.4 port of the official PHP MCP SDK.
 *
 * Generated by bin/port from the Mcp\Schema namespace of mcp/sdk — change the
 * upstream source, or runtime/, and re-run it rather than editing this file.
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Mcp\Schema;

use Mcp\Exception\InvalidArgumentException;
use Mcp\Schema\Enum\ToolChoiceMode;

/**
 * Controls how the model uses tools during sampling.
 *
 * @deprecated since protocol revision 2026-07-28 (SEP-2577), earliest removal 2027-07-28.
 *  Integrate with an LLM provider's API directly instead.
 */
final class ToolChoice implements \JsonSerializable
{
    /**
     * @readonly
     */
    public ToolChoiceMode $mode;

    public function __construct(?ToolChoiceMode $mode = null)
    {
        $mode = $mode ?? ToolChoiceMode::Auto();
        $this->mode = $mode;
    }

    /**
     * @param array{mode?: string} $data
     */
    public static function fromArray(array $data): self
    {
        if (\array_key_exists('mode', $data) && !\is_string($data['mode'])) {
            throw new InvalidArgumentException('Invalid "mode" in ToolChoice data.');
        }

        $mode = \array_key_exists('mode', $data) ? ToolChoiceMode::tryFrom($data['mode']) : ToolChoiceMode::Auto();
        if (null === $mode) {
            throw new InvalidArgumentException(\sprintf('Invalid tool choice mode "%s".', $data['mode']));
        }

        return new self($mode);
    }

    /**
     * @return array{mode: string}
     */
    public function jsonSerialize(): array
    {
        return ['mode' => $this->mode->value];
    }
}
